### ISSUE TITLE
Update Dogon spreadsheet

### ISSUE THREAD

**Issue by bambooforest** [clld/dogonlanguages-data#10]

**Comment by xrotwang** [comment]
How much do you think it has changed?

**Comment by bambooforest** [comment]
I had a quick look and it adds lexical items for a bunch of languages. Perhaps it's better to just add the new spreadsheet and wait for a website update until Jeff is done in the field this year. He said something to me recently along the lines of, I spent the last year killing myself finishing 10 grammars. So there should be quite a bit of update in general. And there seems to be several languages (Bunoge (Boudou), Penange (Pinia), Dogul Dom, Tebul Ure) for which we have the flora and fauna vocab, but not the other forms in the lexical spreadsheet.
