### ISSUE TITLE
Kindige

### ISSUE THREAD

**Issue by bambooforest** [clld/dogonlanguages-data#11]
From Abbie:

> I was just looking at the webpage (which is really looking nice btw) and noticed that here http://dogonlanguages.org/languages/bond1248 it says that Kindige has not yet been studied in depth. Could we modify that statement to include a reference to this:
>
> https://cdstar.shh.mpg.de/bitstreams/EAEA0-B30A-7ABC-7397-0/a.pdf
>
> I can also include interlinearized texts and a lexicon if they're not already on the site.

**Comment by xrotwang** [comment]
@bambooforest so what are we supposed to do here? The grammar is already linked from "materials": http://dogonlanguages.org/sources/hantgan2013kindigue
Just update the language description text?

**Comment by bambooforest** [comment]
@xrotwang How about:

(exonym Bondu So) is thought to be a single language with much dialectal diversity, but Kindige has not yet been studied in depth beyond initial fieldwork by Abbie Hantgan (see: [https://cdstar.shh.mpg.de/bitstreams/EAEA0-B30A-7ABC-7397-0/a.pdf](https://cdstar.shh.mpg.de/bitstreams/EAEA0-B30A-7ABC-7397-0/a.pdf). Najamba is the local name for the language in several villages in a large canyon beginning just east of Douentza and ending at the huge central Dogon plateau (e.g. Kubewel, Adia). Kindige is an informal local name for the dialects spoken along the highway running west from Douentza (separated from Najamba by a long inselberg and then by the plateau) and into the high plateau including the Borko area.

Or instead a link to the bibliography entry: Hantgan2013Kindigue

(I will update the bibliography's links.)
