### ISSUE TITLE
Missing doc

### ISSUE THREAD

**Issue by bambooforest** [clld/dogonlanguages-data#15]
This URL doesn't resolve (Najamba texts):

https://cdstar.shh.mpg.de/bitstreams/EAEA0-A9EB-9B90-A9E8-0/a.doc

**Comment by xrotwang** [comment]
Do we have an idea what it should resolve to?

**Comment by xrotwang** [comment]
I guess this is an artifact of me trying to download everything linked on the old dogonlanguages.org and failing to check HTTP status codes - or, also possible, the server delivering the error page in the doc using HTTP 200.

**Comment by bambooforest** [comment]
I'm searching for the texts but don't have them on my local machine.

**Comment by bambooforest** [comment]
@xrotwang I uploaded the pdf here:

https://github.com/clld/dogonlanguages-data/blob/master/beta/literature/Heath_Najamba_texts_2005_Adia_complete.pdf

**Comment by bambooforest** [comment]
Links fixed here:

https://github.com/clld/dogonlanguages-data/commit/794dd6b53da2b20f2daa92cef0b9111f137ab045

Issue closed once website is regenerated.
